### ISSUE TITLE
Players sometimes get timed out error message after 3-4 seconds

### ISSUE THREAD

**Issue by FixTheAdmin** [TyphoonMC/TyphoonCore#13]
Players sometime get disconnected with a timed out error message shortly after joining. This happens in about 1/10 joins. They will not get disconnected if they manage to be online for more than 5 seconds.

Tested on both 1.14 and 1.13.2 versions.

**Comment by skyforce77** [comment]
Duplicated: https://github.com/TyphoonMC/TyphoonCore/issues/8
