### ISSUE TITLE
Please create a new release to fix the Go module issue

### ISSUE THREAD

**Issue by ghost** [TyphoonMC/TyphoonCore#18]
Greetings!

I tried compiling TyphoonLimbo and encountered an issue which states as followed:
```
~/dev/tmp/TyphoonLimbo $ go build
go: finding github.com/TyphoonMC/TyphoonCore v0.0.2
go: finding github.com/TyphoonMC/go.uuid v1.2.0
go: github.com/TyphoonMC/TyphoonLimbo imports
	github.com/TyphoonMC/TyphoonCore: github.com/TyphoonMC/TyphoonCore@v0.0.2: parsing go.mod:
	module declares its path as: TyphoonCore
	        but was required as: github.com/TyphoonMC/TyphoonCore
```
This issue occurs because Go attempts to fetch the 0.0.2 version of this repository. Back in April, the `go.mod` file of this repository declared the module like this: `module TyphoonCore` but was required to be like this `module github.com/TyphoonMC/TyphoonCore` which it is now.

```
~/go/pkg/mod/github.com/!typhoon!m!c/!typhoon!core@v0.0.2 $ grep -r "TyphoonCore"
go.mod:module TyphoonCore
README.md:# TyphoonCore
README.md:[![Build Status](https://travis-ci.org/TyphoonMC/TyphoonLimbo.svg?branch=master)](https://travis-ci.org/TyphoonMC/TyphoonCore)
README.md:TyphoonCore is able to load [TyphoonDep protocol-map modules](https://github.com/TyphoonMC/TyphoonDep/tree/master/protocol-map) to add a partial snapshots support.
README.md:go get github.com/TyphoonMC/TyphoonCore
README.md:	t "github.com/TyphoonMC/TyphoonCore"
.gitignore:TyphoonCore

```

Please create a new release (v0.0.3?) to include the changes you made to the `go.mod` file, otherwise you'll have to manually reconfigure the `go.mod` file of the package in your Go directory every time your clone it or gets cloned.

**Comment by jackmawer** [comment]
Hi, looks like a new release has been uploaded so this issue can be closed.
