### ISSUE TITLE
Keepalive packets aren't handled properly

### ISSUE THREAD

**Issue by mikroskeem** [TyphoonMC/TyphoonCore#8]
I haven't investigated much, but sometimes clients simply time out and get disconnected - that in localhost, where latency is <1ms

This happens on about 1/4 connections.

**Comment by FixTheAdmin** [comment]
I'm also having this issue

**Comment by Aang23** [comment]
Same issue here. When using a modded client, which can take longer to login, the client always times out.

Removing 
`if player.keepalive != 0 {
					player.Kick("Timed out")
}`
fixes the issue... But that's far from being a clean fix.

**Comment by mikroskeem** [comment]
Any updates on this? I might get my hands on it on this weekend if nobody wants to look into this issue.

**Comment by skyforce77** [comment]
That's an issue I have had from the very begining of the project. I've never been able to find how to fix it

**Comment by RikoDEV** [comment]
https://github.com/DevKrieger/DKBans/issues/11

**Comment by mikroskeem** [comment]
Absolutely unrelated issue...
